export interface FreelancerProfileInitialState {
  profile_picture: string | null;
  job_title: string | null;
  bio_text: string | null;
  bio_video: string | null;
  location: string | null;
  website: string | null;
  linkedin: string | null;
  github: string | null;
  skills: any | null;
  experience: any | null;
  education: any | null;
  certifications: any | null;
  projects: any | null;
  languages: any | null;
  interests: any | null;
  resume: string | null;
  portfolio: string | null;
  availability: any | null;
  services: any | null;
  hourly_price: string | null;
  first_name: string | null;
  last_name: string | null;
  gender: string | null;
  date_of_birth: string | null;
}
